# Generated by Django 2.2.7 on 2019-11-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginlog',
            old_name='session_id',
            new_name='session',
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='logout',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
