# Generated by Django 2.2.7 on 2019-11-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191125_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created',
        ),
    ]
